### ISSUE TITLE
[ENHANCEMENT] parameter `root_volume_size` not wired to ASG parameter

### ISSUE THREAD

**Issue by orisgarno** [traveloka/terraform-aws-tvlk-bastion#13]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description
Currently SRS need to run a script which need to partially load data from elastic search. We hit the limit of root device space, 8gb.

### New or Affected Resource(s)

* aws-autoscaling_bastion_asg

### Potential Terraform Configuration Changes

Pass parameter to autoscaling_bastion_asg module
```hcl
module "aws-autoscaling_bastion_asg" {
  ...
  ...
  volume_size = "${var.root_volume_size}"
}
```

### References

* #0000

**Comment by nin9swells** [comment]
Can you gives us the detailed use case?

If I'm not wrong, ElasticSearch could load/dump the data directly to/from S3 bucket. If the case is ES, then you can use that built-in feature, can't you?

In general, if there is built-in feature to load/dump data that doesn't involve EBS in bastion, I think going with that feature will be better.

If there is no built-in feature available, then ... rather than increasing root volume, personally I prefer to add extra data volume that you can delete later. -- Although if you increased root volume, you can also delete the whole EC2 instance, and recreate with a smaller disk once you don't need that much volume anymore.

**Comment by sshvetsov** [comment]
Hi @orisgarno,

If I understand correctly, you want ability to increase root volume of the bastion instance, so you have scratch space to temporarily store data transiting through the bastion.

As @nin9swells pointed out, if you must increase the amount of EBS storage available to the bastion, it would be better to manually attach a temporary data volume of required size when you actually need it, instead of changing size of the root volume in your configuration (which likely means it will be larger than required default **every time** you launch your bastion).

I also think you can satisfy your requirements without relying on expensive SDD disk. As @nin9swells already mentioned, [ElasticSearch supports backup/restore directly to/from S3](https://aws.amazon.com/blogs/database/use-amazon-s3-to-store-a-single-amazon-elasticsearch-service-index/). Aurora Postgres now supports [data Import from Amazon S3](https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-aurora-with-postgresql-compatibility-supports-data-import-from-amazon-s3/). Data load to/from other services can likely be satisfied by [piping contents of S3 object via stdin/stout pipes in command line](https://loige.co/aws-command-line-s3-content-from-stdin-or-to-stdout/).

S3 is more than 4 times cheaper than EBS per GB of data stored. Unlike S3, EBS is priced based on GB of storage _provisioned_ (even if you don't use any data).

My recommendation would be to leave "root_volume_size" parameter hidden and consider more cost effective alternatives.

**Comment by orisgarno** [comment]
Hi, i already solved my problem regarding volume size for bastion.
We update our script to do the job batch by batch, it also help to decrease bastion memory usage.
