### ISSUE TITLE
Update default AMI prefix to use newer Ubuntu version

### ISSUE THREAD

**Issue by narayananvenk** [traveloka/terraform-aws-tvlk-bastion#30]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

***

### Question

The current [default](https://github.com/traveloka/terraform-aws-tvlk-bastion/blob/master/variables.tf#L52) AMI prefix in the module uses `ubuntu-14` which has already reached end of support. I'd like to bump up this value to the next available stable release which is `ubuntu-16`. This will allow teams creating bastions to use supported AMIs if they don't override the default.

I have a commit [here](https://github.com/traveloka/terraform-aws-tvlk-bastion/commit/b5d58ca7781f56a5377773651cdd12fb361260c8) which I can convert to a PR if it's ok to change this default value.

**Comment by narayananvenk** [comment]
Requesting a check from @sumodirjo / @aashari (based on recent commit history) as I'm not able to add assignees.

**Comment by sshvetsov** [comment]
Thanks for suggestion @narayananvenk, it's appreciated.

If we're going to keep a default value for `ami_name_prefix` variable at all, I think it should be bumped to `tvlk/ubuntu-20/tsi/bastion*`, since that is the latest and recommended version for Bastion AMI.

You may also want to update the value you configured for `ami_owner_account_id` in your Terraform stacks, since we have moved our AMI production form `tvlk-tsi-dev` account to `tvlk-tsi-prod` account (which could be why you were not noticing the Ubuntu 20 AMIs).

**Comment by sshvetsov** [comment]
@narayananvenk I made a comment on your commit, please do submit it as a PR. Thanks.

**Comment by narayananvenk** [comment]
Opened a PR with some minor questions.

One a related note, the Github [action](https://github.com/traveloka/terraform-aws-tvlk-bastion/actions/runs/666551945) while opening issues on this repo seems to fail.
